[host]
# 测试环境
API_HOST = http://192.168.1.90:8085

[admin]
username = admin
password = macro123

[mysql]
# MySQL配置
MYSQL_HOST = 192.168.1.90
MYSQL_PORT = 3306
MYSQL_USER = root
MYSQL_PASSWD = root
MYSQL_DB = mall

[redis]
HOST = 192.168.1.90
PORT = 6379
PASSWORD =
DATABASE = MALL